package com.sxit.model.log;

// Generated 2014-7-8 14:06:43 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * TintOperator generated by hbm2java
 */

public class TintOperator implements java.io.Serializable {

	/**
	 * 操作id.
	 */
	private Integer operatorId;
	/**
	 * 系统版本号.
	 */
	private String versionNum;
	/**
	 * 应用版本号.
	 */
	private String appVersionNum;
	/**
	 * 用户ID.
	 */
	private String userId;
	/**
	 * 用户名.
	 */
	private String userName;
	/**
	 * 接口名称.
	 */
	private String reqUrl;
	/**
	 * 接口名称.
	 */
	private String intName;
	/**
	 * 请求数据.
	 */
	private String reqData;
	/**
	 * 返回数据.
	 */
	private String resData;
	/**
	 * 请求内容.
	 */
	private String reqContent;
	/**
	 * 返回内容.
	 */
	private String resContent;
	/**
	 * 异常信息.
	 */
	private String excData;
	/**
	 * IP地址.
	 */
	private String ip;
	/**
	 * imei.
	 */
	private String imei;
	/**
	 * 型号.
	 */
	private String modelNum;
	/**
	 * 类型 |radio@resultMaps#'1':'微站'2':'客户端','3':'管理台'.
	 */
	private Integer type;
	/**
	 * 操作结果 |radio@resultMaps#'1':'成功','2':'失败','3':'异常'.
	 */
	private Integer result;
	/**
	 * 时间|datetime.
	 */
	private Date createTime;

	public TintOperator() {
	}

	public TintOperator(String reqUrl, String ip) {
		this.reqUrl = reqUrl;
		this.ip = ip;
		this.createTime = new Date();
	}

	public TintOperator(String userId, String userName, String reqUrl,
			String intName, String reqData, String resData, String reqContent,
			String resContent, String excData, String ip, String imei,
			String modelNum, Integer type, Integer result, Date createTime) {
		this.userId = userId;
		this.userName = userName;
		this.reqUrl = reqUrl;
		this.intName = intName;
		this.reqData = reqData;
		this.resData = resData;
		this.reqContent = reqContent;
		this.resContent = resContent;
		this.excData = excData;
		this.ip = ip;
		this.imei = imei;
		this.modelNum = modelNum;
		this.type = type;
		this.result = result;
		this.createTime = createTime;
	}

	public Integer getOperatorId() {
		return operatorId;
	}

	public void setOperatorId(Integer operatorId) {
		this.operatorId = operatorId;
	}

	public String getVersionNum() {
		return versionNum;
	}

	public void setVersionNum(String versionNum) {
		this.versionNum = versionNum;
	}

	public String getAppVersionNum() {
		return appVersionNum;
	}

	public void setAppVersionNum(String appVersionNum) {
		this.appVersionNum = appVersionNum;
	}

	public String getUserId() {
		return userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getReqUrl() {
		return reqUrl;
	}

	public void setReqUrl(String reqUrl) {
		this.reqUrl = reqUrl;
	}

	public String getIntName() {
		return intName;
	}

	public void setIntName(String intName) {
		this.intName = intName;
	}

	public String getReqData() {
		return reqData;
	}

	public void setReqData(String reqData) {
		this.reqData = reqData;
	}

	public String getResData() {
		return resData;
	}

	public void setResData(String resData) {
		this.resData = resData;
	}

	public String getReqContent() {
		return reqContent;
	}

	public void setReqContent(String reqContent) {
		this.reqContent = reqContent;
	}

	public String getResContent() {
		return resContent;
	}

	public void setResContent(String resContent) {
		this.resContent = resContent;
	}

	public String getExcData() {
		return excData;
	}

	public void setExcData(String excData) {
		this.excData = excData;
	}

	public String getIp() {
		return ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getImei() {
		return imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getModelNum() {
		return modelNum;
	}

	public void setModelNum(String modelNum) {
		this.modelNum = modelNum;
	}

	public Integer getType() {
		return type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	public Integer getResult() {
		return result;
	}

	public void setResult(Integer result) {
		this.result = result;
	}

	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}


}
